"""PDF Report Generator for Azure Updates Intelligence.

Produces a professional, colour-coded PDF report using fpdf2.

Report structure:
  - Cover page with subscription summary and generation date
  - Executive summary with key metrics
  - Per-section pages with updates grouped by priority
  - Each update shows title, status, relevance, affected resources, link

Section colours are derived from priority rank rather than hardcoded
to specific section names.
"""

from __future__ import annotations

import json
import logging
import os
import tempfile
from datetime import datetime, timezone
from typing import Any

from azure_cost_mcp.response import error_response, success_response
from azure_cost_mcp.tools.update_intelligence import get_personalized_updates

logger = logging.getLogger(__name__)

# ── Colour Palette (by priority rank) ────────────────────────────────
# Priority 1-2: urgent/critical (reds/oranges)
# Priority 3-4: informational/cost (blues/greens)
# Priority 5-6: preview/regional (purples/teals)
# 99+: other (greys)
_PRIORITY_COLORS = {
    1: (220, 53, 69),     # Red — Retirements / Action Required
    2: (255, 140, 0),     # Orange — Security
    3: (40, 167, 69),     # Green — Cost / Pricing
    4: (0, 123, 255),     # Blue — New features / GA
    5: (111, 66, 193),    # Purple — Preview / Upcoming
    6: (23, 162, 184),    # Teal — Regional Expansion
    99: (108, 117, 125),  # Grey — Other
}


def _get_section_color(priority: int) -> tuple[int, int, int]:
    """Get the RGB colour for a section based on its priority rank."""
    return _PRIORITY_COLORS.get(priority, _PRIORITY_COLORS[99])


def _truncate(text: str, max_len: int = 120) -> str:
    """Truncate text to max_len and add ellipsis if needed."""
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."


# ── PDF Generation ───────────────────────────────────────────────────


def _build_pdf(
    digest: dict[str, Any],
    report_type: str = "full",
) -> bytes:
    """Build the PDF document and return the raw bytes.

    Args:
        digest: The personalized updates digest (parsed JSON).
        report_type: 'full' or 'executive' (summary only, no per-update details).

    Returns:
        Raw PDF bytes.
    """
    from fpdf import FPDF

    class AzureUpdatesPDF(FPDF):
        """Custom FPDF subclass with header/footer."""

        def header(self):
            if self.page_no() > 1:
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(108, 117, 125)
                self.cell(0, 6, "Azure Updates Intelligence Report", align="L")
                self.cell(0, 6, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
                self.line(10, 16, 200, 16)
                self.ln(4)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 7)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, "Generated by Azure Cost Management MCP Server", align="C")

    pdf = AzureUpdatesPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(15, 15, 15)

    sub_summary = digest.get("subscription_summary", {})
    dig_summary = digest.get("digest_summary", {})
    sections = digest.get("sections", [])

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # ── Cover Page ────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(0, 102, 204)
    pdf.ln(40)
    pdf.cell(0, 15, "Azure Updates", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 20)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 12, "Intelligence Report", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)
    pdf.set_draw_color(0, 102, 204)
    pdf.set_line_width(0.8)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(12)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    sub_id = sub_summary.get("subscription_id", "N/A")
    pdf.cell(0, 7, f"Subscription: {sub_id}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0, 7,
        f"Resources: {sub_summary.get('total_resources', 0)} across "
        f"{sub_summary.get('unique_resource_types', 0)} resource types",
        align="C", new_x="LMARGIN", new_y="NEXT",
    )
    pdf.cell(0, 7, f"Generated: {timestamp}", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(20)

    # Top services
    top_services = sub_summary.get("top_services", [])
    if top_services:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(0, 8, "Top Deployed Services:", align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for svc in top_services[:8]:
            pdf.cell(0, 6, f"  {svc}", align="C", new_x="LMARGIN", new_y="NEXT")

    # ── Executive Summary ─────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(0, 12, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(40, 40, 40)

    total_feed = dig_summary.get("total_feed_updates", 0)
    relevant = dig_summary.get("relevant_updates", 0)
    action_req = dig_summary.get("action_required", 0)
    num_sections = dig_summary.get("sections", 0)

    metrics = [
        ("Total Azure Updates in Feed", str(total_feed)),
        ("Updates Relevant to Your Environment", str(relevant)),
        ("Action Required (Urgent)", str(action_req)),
        ("Categories Identified", str(num_sections)),
    ]

    for label, value in metrics:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(120, 8, f"  {label}:")
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, value, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(6)

    # Section overview table
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 10, "Sections Overview", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    for section in sections:
        color = _get_section_color(section.get("priority", 99))
        pdf.set_fill_color(*color)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 10)
        section_name = section.get("section", "Unknown")
        count = section.get("count", 0)
        pdf.cell(0, 8, f"  {section_name} ({count} updates)", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(40, 40, 40)
        pdf.ln(1)

    if report_type == "executive":
        return pdf.output()

    # ── Per-Section Detail Pages ──────────────────────────────────
    for section in sections:
        color = _get_section_color(section.get("priority", 99))
        section_name = section.get("section", "Unknown")
        updates = section.get("updates", [])

        pdf.add_page()

        # Section header bar
        pdf.set_fill_color(*color)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, f"  {section_name}", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        for i, update in enumerate(updates, 1):
            # Check if we need a new page (rough estimate)
            if pdf.get_y() > 245:
                pdf.add_page()
                # Re-draw section header on continuation
                pdf.set_fill_color(*color)
                pdf.set_text_color(255, 255, 255)
                pdf.set_font("Helvetica", "B", 14)
                pdf.cell(0, 10, f"  {section_name} (continued)", fill=True, new_x="LMARGIN", new_y="NEXT")
                pdf.ln(4)

            title = update.get("title", "Untitled")
            status = update.get("status", "Unknown")
            relevance = update.get("relevance_score", 0)
            link = update.get("link", "")
            affected = update.get("affected_resources", [])
            total_affected = update.get("total_affected_count", 0)
            services = update.get("service_categories", [])

            # Update title
            pdf.set_text_color(30, 30, 30)
            pdf.set_font("Helvetica", "B", 10)
            pdf.multi_cell(0, 6, f"{i}. {_truncate(title, 150)}", new_x="LMARGIN", new_y="NEXT")

            # Metadata line
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(100, 100, 100)

            meta_parts = [f"Status: {status}"]
            if relevance:
                meta_parts.append(f"Relevance: {relevance:.1%}")
            if total_affected:
                meta_parts.append(f"Affected resources: {total_affected}")
            if services:
                meta_parts.append(f"Services: {', '.join(services[:3])}")

            pdf.cell(0, 5, "   ".join(meta_parts), new_x="LMARGIN", new_y="NEXT")

            # Affected resource types
            if affected:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(80, 80, 80)
                for ar in affected[:3]:
                    svc_name = ar.get("service_name", ar.get("resource_type", ""))
                    rc = ar.get("resource_count", 0)
                    locs = ", ".join(ar.get("locations", [])[:3])
                    pdf.cell(
                        0, 4,
                        f"      {svc_name} ({rc} resources) — {locs}",
                        new_x="LMARGIN", new_y="NEXT",
                    )

            # Link
            if link:
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(0, 102, 204)
                pdf.cell(0, 5, f"   {_truncate(link, 100)}", link=link, new_x="LMARGIN", new_y="NEXT")

            pdf.ln(3)

    return pdf.output()


# ── Public API ───────────────────────────────────────────────────────


async def generate_report(
    subscription_id: str | None = None,
    report_type: str = "full",
    max_per_section: int = 10,
    output_path: str | None = None,
) -> str:
    """Generate a PDF report of personalised Azure Updates.

    Args:
        subscription_id: Azure subscription ID (defaults to AZURE_SUBSCRIPTION_ID).
        report_type: 'full' (detailed per-update) or 'executive' (summary only).
        max_per_section: Maximum updates per section in the digest.
        output_path: File path to save the PDF. Defaults to a temp file.

    Returns:
        JSON with the file path of the generated PDF and summary stats.
    """
    try:
        # Get the personalized digest
        digest_json = await get_personalized_updates(
            subscription_id=subscription_id,
            max_per_section=max_per_section,
        )
        digest = json.loads(digest_json)

        if digest.get("status") != "success":
            return error_response(
                "Failed to generate updates digest: "
                + digest.get("error", {}).get("message", "Unknown error")
            )

        digest_data = digest["data"]

        # Build the PDF
        pdf_bytes = _build_pdf(digest_data, report_type=report_type)

        # Determine output path
        if not output_path:
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            output_path = os.path.join(
                tempfile.gettempdir(),
                f"azure_updates_report_{timestamp}.pdf",
            )

        # Write to file
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)

        sub_summary = digest_data.get("subscription_summary", {})
        dig_summary = digest_data.get("digest_summary", {})

        return success_response(
            {
                "report_path": output_path,
                "report_type": report_type,
                "file_size_bytes": len(pdf_bytes),
                "subscription_id": sub_summary.get("subscription_id", ""),
                "total_resources": sub_summary.get("total_resources", 0),
                "relevant_updates": dig_summary.get("relevant_updates", 0),
                "sections": dig_summary.get("sections", 0),
                "action_required": dig_summary.get("action_required", 0),
            },
            scope=f"subscriptions/{sub_summary.get('subscription_id', '')}",
            extra_meta={
                "reportType": report_type,
                "maxPerSection": max_per_section,
            },
        )
    except ImportError:
        logger.exception("fpdf2 not installed")
        return error_response(
            "fpdf2 is required for PDF generation. Install it with: pip install fpdf2>=2.7.0",
            code="MissingDependency",
        )
    except Exception as e:
        logger.exception("generate_report failed")
        return error_response(str(e))
